/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) landing_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {9, 1, 1};

/* landing_expl_vde_adj:(i0[6],i1[6],i2[3],i3[0])->(o0[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w00=w+0, *w01=w+6, w02, w03, w04, w05, w06, *w07=w+17, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, *w16=w+31, w17, w18, w19, w20, w21, w22;
  casadi_real w23, w24;
  const casadi_real *cs;
  /* #0: @0 = zeros(6x1) */
  casadi_clear(w00, 6);
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 6, w01);
  /* #2: @2 = @1[5] */
  for (rr=(&w02), cs=w01+5; cs!=w01+6; cs+=1) *rr++ = *cs;
  /* #3: @3 = sin(@2) */
  w03 = sin( w02 );
  /* #4: @4 = 9.81 */
  w04 = 9.8100000000000005e+00;
  /* #5: @5 = @1[3] */
  for (rr=(&w05), cs=w01+3; cs!=w01+4; cs+=1) *rr++ = *cs;
  /* #6: @6 = (@4/@5) */
  w06  = (w04/w05);
  /* #7: @7 = input[1][0] */
  casadi_copy(arg[1], 6, w07);
  /* #8: {@8, @9, @10, @11, @12, @13} = vertsplit(@7) */
  w08 = w07[0];
  w09 = w07[1];
  w10 = w07[2];
  w11 = w07[3];
  w12 = w07[4];
  w13 = w07[5];
  /* #9: @14 = (@6*@13) */
  w14  = (w06*w13);
  /* #10: @15 = (@3*@14) */
  w15  = (w03*w14);
  /* #11: @16 = input[2][0] */
  casadi_copy(arg[2], 3, w16);
  /* #12: @17 = @16[1] */
  for (rr=(&w17), cs=w16+1; cs!=w16+2; cs+=1) *rr++ = *cs;
  /* #13: @18 = (@4*@17) */
  w18  = (w04*w17);
  /* #14: @18 = (@18/@5) */
  w18 /= w05;
  /* #15: @19 = @16[2] */
  for (rr=(&w19), cs=w16+2; cs!=w16+3; cs+=1) *rr++ = *cs;
  /* #16: @20 = sin(@19) */
  w20 = sin( w19 );
  /* #17: @21 = (@18*@20) */
  w21  = (w18*w20);
  /* #18: @2 = cos(@2) */
  w02 = cos( w02 );
  /* #19: @21 = (@21/@2) */
  w21 /= w02;
  /* #20: @21 = (@21/@2) */
  w21 /= w02;
  /* #21: @21 = (@21*@12) */
  w21 *= w12;
  /* #22: @21 = (@3*@21) */
  w21  = (w03*w21);
  /* #23: @15 = (@15+@21) */
  w15 += w21;
  /* #24: @11 = (@4*@11) */
  w11  = (w04*w11);
  /* #25: @21 = (@2*@11) */
  w21  = (w02*w11);
  /* #26: @15 = (@15-@21) */
  w15 -= w21;
  /* #27: @21 = (@5*@10) */
  w21  = (w05*w10);
  /* #28: @21 = (@2*@21) */
  w21  = (w02*w21);
  /* #29: @15 = (@15+@21) */
  w15 += w21;
  /* #30: @21 = @1[4] */
  for (rr=(&w21), cs=w01+4; cs!=w01+5; cs+=1) *rr++ = *cs;
  /* #31: @22 = sin(@21) */
  w22 = sin( w21 );
  /* #32: @23 = (@5*@22) */
  w23  = (w05*w22);
  /* #33: @23 = (@23*@9) */
  w23 *= w09;
  /* #34: @23 = (@3*@23) */
  w23  = (w03*w23);
  /* #35: @15 = (@15-@23) */
  w15 -= w23;
  /* #36: @21 = cos(@21) */
  w21 = cos( w21 );
  /* #37: @23 = (@5*@21) */
  w23  = (w05*w21);
  /* #38: @23 = (@23*@8) */
  w23 *= w08;
  /* #39: @23 = (@3*@23) */
  w23  = (w03*w23);
  /* #40: @15 = (@15-@23) */
  w15 -= w23;
  /* #41: (@0[5] += @15) */
  for (rr=w00+5, cs=(&w15); rr!=w00+6; rr+=1) *rr += *cs++;
  /* #42: @9 = (@2*@9) */
  w09  = (w02*w09);
  /* #43: @15 = (@5*@9) */
  w15  = (w05*w09);
  /* #44: @15 = (@21*@15) */
  w15  = (w21*w15);
  /* #45: @8 = (@2*@8) */
  w08  = (w02*w08);
  /* #46: @23 = (@5*@8) */
  w23  = (w05*w08);
  /* #47: @23 = (@22*@23) */
  w23  = (w22*w23);
  /* #48: @15 = (@15-@23) */
  w15 -= w23;
  /* #49: (@0[4] += @15) */
  for (rr=w00+4, cs=(&w15); rr!=w00+5; rr+=1) *rr += *cs++;
  /* #50: @15 = (@18/@5) */
  w15  = (w18/w05);
  /* #51: @12 = (@12/@2) */
  w12 /= w02;
  /* #52: @23 = (@20*@12) */
  w23  = (w20*w12);
  /* #53: @15 = (@15*@23) */
  w15 *= w23;
  /* #54: @15 = (-@15) */
  w15 = (- w15 );
  /* #55: @6 = (@6/@5) */
  w06 /= w05;
  /* #56: @19 = cos(@19) */
  w19 = cos( w19 );
  /* #57: @24 = (@17*@19) */
  w24  = (w17*w19);
  /* #58: @24 = (@24-@2) */
  w24 -= w02;
  /* #59: @24 = (@24*@13) */
  w24 *= w13;
  /* #60: @6 = (@6*@24) */
  w06 *= w24;
  /* #61: @15 = (@15-@6) */
  w15 -= w06;
  /* #62: @3 = (@3*@10) */
  w03 *= w10;
  /* #63: @15 = (@15+@3) */
  w15 += w03;
  /* #64: @22 = (@22*@9) */
  w22 *= w09;
  /* #65: @15 = (@15+@22) */
  w15 += w22;
  /* #66: @21 = (@21*@8) */
  w21 *= w08;
  /* #67: @15 = (@15+@21) */
  w15 += w21;
  /* #68: (@0[3] += @15) */
  for (rr=w00+3, cs=(&w15); rr!=w00+4; rr+=1) *rr += *cs++;
  /* #69: output[0][0] = @0 */
  casadi_copy(w00, 6, res[0]);
  /* #70: @16 = zeros(3x1) */
  casadi_clear(w16, 3);
  /* #71: @18 = (@18*@12) */
  w18 *= w12;
  /* #72: @18 = (@19*@18) */
  w18  = (w19*w18);
  /* #73: @17 = (@17*@14) */
  w17 *= w14;
  /* #74: @20 = (@20*@17) */
  w20 *= w17;
  /* #75: @18 = (@18-@20) */
  w18 -= w20;
  /* #76: (@16[2] += @18) */
  for (rr=w16+2, cs=(&w18); rr!=w16+3; rr+=1) *rr += *cs++;
  /* #77: @19 = (@19*@14) */
  w19 *= w14;
  /* #78: @23 = (@23/@5) */
  w23 /= w05;
  /* #79: @4 = (@4*@23) */
  w04 *= w23;
  /* #80: @19 = (@19+@4) */
  w19 += w04;
  /* #81: (@16[1] += @19) */
  for (rr=w16+1, cs=(&w19); rr!=w16+2; rr+=1) *rr += *cs++;
  /* #82: (@16[0] += @11) */
  for (rr=w16+0, cs=(&w11); rr!=w16+1; rr+=1) *rr += *cs++;
  /* #83: output[0][1] = @16 */
  if (res[0]) casadi_copy(w16, 3, res[0]+6);
  return 0;
}

CASADI_SYMBOL_EXPORT int landing_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int landing_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int landing_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void landing_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int landing_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void landing_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void landing_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void landing_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int landing_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int landing_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real landing_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* landing_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* landing_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* landing_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* landing_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int landing_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 42;
  return 0;
}

CASADI_SYMBOL_EXPORT int landing_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 42*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
