/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) landing_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[27] = 
  {9, 6, 0, 3, 6, 9, 12, 15,
  18, 3, 4, 5, 3, 4, 5, 3,
  4, 5, 3, 4, 5, 3, 4, 5,
  3, 4, 5};
static const casadi_int casadi_s4[3] = {6, 0, 1};

/* landing_constr_h_fun_jac_uxt_zt:(i0[6],i1[3],i2[0],i3[0])->(o0[6],o1[9x6,18nz],o2[6x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w00=w+0, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, *w18=w+23, *w19=w+41, *w20=w+48;
  const casadi_real *cs;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 6, w00);
  /* #1: @1 = @0[0] */
  for (rr=(&w01), cs=w00+0; cs!=w00+1; cs+=1) *rr++ = *cs;
  /* #2: @2 = 429.591 */
  w02 = 4.2959100779586987e+02;
  /* #3: @2 = (@1-@2) */
  w02  = (w01-w02);
  /* #4: @3 = 10 */
  w03 = 10.;
  /* #5: @2 = (@2/@3) */
  w02 /= w03;
  /* #6: @4 = sq(@2) */
  w04 = casadi_sq( w02 );
  /* #7: @5 = @0[1] */
  for (rr=(&w05), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #8: @6 = 1.00549 */
  w06 = 1.0054866686369497e+00;
  /* #9: @6 = (@5-@6) */
  w06  = (w05-w06);
  /* #10: @6 = (@6/@3) */
  w06 /= w03;
  /* #11: @7 = sq(@6) */
  w07 = casadi_sq( w06 );
  /* #12: @4 = (@4+@7) */
  w04 += w07;
  /* #13: @7 = @0[2] */
  for (rr=(&w07), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #14: @7 = (@7/@3) */
  w07 /= w03;
  /* #15: @8 = sq(@7) */
  w08 = casadi_sq( w07 );
  /* #16: @4 = (@4+@8) */
  w04 += w08;
  /* #17: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #18: @4 = 636.034 */
  w04 = 6.3603435348412086e+02;
  /* #19: @4 = (@1-@4) */
  w04  = (w01-w04);
  /* #20: @4 = (@4/@3) */
  w04 /= w03;
  /* #21: @9 = sq(@4) */
  w09 = casadi_sq( w04 );
  /* #22: @10 = -11.3322 */
  w10 = -1.1332166779991979e+01;
  /* #23: @10 = (@5-@10) */
  w10  = (w05-w10);
  /* #24: @10 = (@10/@3) */
  w10 /= w03;
  /* #25: @11 = sq(@10) */
  w11 = casadi_sq( w10 );
  /* #26: @9 = (@9+@11) */
  w09 += w11;
  /* #27: @9 = (@9+@8) */
  w09 += w08;
  /* #28: output[0][1] = @9 */
  if (res[0]) res[0][1] = w09;
  /* #29: @9 = 788.981 */
  w09 = 7.8898109327178634e+02;
  /* #30: @9 = (@1-@9) */
  w09  = (w01-w09);
  /* #31: @9 = (@9/@3) */
  w09 /= w03;
  /* #32: @11 = sq(@9) */
  w11 = casadi_sq( w09 );
  /* #33: @12 = 7.66679 */
  w12 = 7.6667890767917717e+00;
  /* #34: @12 = (@5-@12) */
  w12  = (w05-w12);
  /* #35: @12 = (@12/@3) */
  w12 /= w03;
  /* #36: @13 = sq(@12) */
  w13 = casadi_sq( w12 );
  /* #37: @11 = (@11+@13) */
  w11 += w13;
  /* #38: @11 = (@11+@8) */
  w11 += w08;
  /* #39: output[0][2] = @11 */
  if (res[0]) res[0][2] = w11;
  /* #40: @11 = 216.185 */
  w11 = 2.1618484626995848e+02;
  /* #41: @11 = (@1-@11) */
  w11  = (w01-w11);
  /* #42: @11 = (@11/@3) */
  w11 /= w03;
  /* #43: @13 = sq(@11) */
  w13 = casadi_sq( w11 );
  /* #44: @14 = 6.10205 */
  w14 = 6.1020453763077107e+00;
  /* #45: @14 = (@5-@14) */
  w14  = (w05-w14);
  /* #46: @14 = (@14/@3) */
  w14 /= w03;
  /* #47: @15 = sq(@14) */
  w15 = casadi_sq( w14 );
  /* #48: @13 = (@13+@15) */
  w13 += w15;
  /* #49: @13 = (@13+@8) */
  w13 += w08;
  /* #50: output[0][3] = @13 */
  if (res[0]) res[0][3] = w13;
  /* #51: @13 = 588.434 */
  w13 = 5.8843362492577830e+02;
  /* #52: @13 = (@1-@13) */
  w13  = (w01-w13);
  /* #53: @13 = (@13/@3) */
  w13 /= w03;
  /* #54: @15 = sq(@13) */
  w15 = casadi_sq( w13 );
  /* #55: @16 = -7.9614 */
  w16 = -7.9613997721557670e+00;
  /* #56: @16 = (@5-@16) */
  w16  = (w05-w16);
  /* #57: @16 = (@16/@3) */
  w16 /= w03;
  /* #58: @17 = sq(@16) */
  w17 = casadi_sq( w16 );
  /* #59: @15 = (@15+@17) */
  w15 += w17;
  /* #60: @15 = (@15+@8) */
  w15 += w08;
  /* #61: output[0][4] = @15 */
  if (res[0]) res[0][4] = w15;
  /* #62: @15 = 751.379 */
  w15 = 7.5137914045529396e+02;
  /* #63: @1 = (@1-@15) */
  w01 -= w15;
  /* #64: @1 = (@1/@3) */
  w01 /= w03;
  /* #65: @15 = sq(@1) */
  w15 = casadi_sq( w01 );
  /* #66: @17 = -3.77704 */
  w17 = -3.7770421770019347e+00;
  /* #67: @5 = (@5-@17) */
  w05 -= w17;
  /* #68: @5 = (@5/@3) */
  w05 /= w03;
  /* #69: @3 = sq(@5) */
  w03 = casadi_sq( w05 );
  /* #70: @15 = (@15+@3) */
  w15 += w03;
  /* #71: @15 = (@15+@8) */
  w15 += w08;
  /* #72: output[0][5] = @15 */
  if (res[0]) res[0][5] = w15;
  /* #73: @18 = zeros(9x6,18nz) */
  casadi_clear(w18, 18);
  /* #74: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #75: @15 = 0.1 */
  w15 = 1.0000000000000001e-01;
  /* #76: @19 = ones(9x1,7nz) */
  casadi_fill(w19, 7, 1.);
  /* #77: {NULL, @20} = vertsplit(@19) */
  casadi_copy(w19+3, 4, w20);
  /* #78: @8 = @20[0] */
  for (rr=(&w08), cs=w20+0; cs!=w20+1; cs+=1) *rr++ = *cs;
  /* #79: @8 = (@15*@8) */
  w08  = (w15*w08);
  /* #80: @2 = (@2*@8) */
  w02 *= w08;
  /* #81: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #82: @4 = (@4*@8) */
  w04 *= w08;
  /* #83: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #84: @9 = (@9*@8) */
  w09 *= w08;
  /* #85: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #86: @11 = (@11*@8) */
  w11 *= w08;
  /* #87: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #88: @13 = (@13*@8) */
  w13 *= w08;
  /* #89: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #90: @1 = (@1*@8) */
  w01 *= w08;
  /* #91: @0 = vertcat(@2, @4, @9, @11, @13, @1) */
  rr=w00;
  *rr++ = w02;
  *rr++ = w04;
  *rr++ = w09;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w01;
  /* #92: (@18[:18:3] = @0) */
  for (rr=w18+0, cs=w00; rr!=w18+18; rr+=3) *rr = *cs++;
  /* #93: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #94: @2 = ones(9x1,1nz) */
  w02 = 1.;
  /* #95: {NULL, @4} = vertsplit(@2) */
  w04 = w02;
  /* #96: @2 = @4[0] */
  for (rr=(&w02), cs=(&w04)+0; cs!=(&w04)+1; cs+=1) *rr++ = *cs;
  /* #97: @2 = (@15*@2) */
  w02  = (w15*w02);
  /* #98: @6 = (@6*@2) */
  w06 *= w02;
  /* #99: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #100: @10 = (@10*@2) */
  w10 *= w02;
  /* #101: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #102: @12 = (@12*@2) */
  w12 *= w02;
  /* #103: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #104: @14 = (@14*@2) */
  w14 *= w02;
  /* #105: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #106: @16 = (@16*@2) */
  w16 *= w02;
  /* #107: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #108: @5 = (@5*@2) */
  w05 *= w02;
  /* #109: @0 = vertcat(@6, @10, @12, @14, @16, @5) */
  rr=w00;
  *rr++ = w06;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w16;
  *rr++ = w05;
  /* #110: (@18[1:19:3] = @0) */
  for (rr=w18+1, cs=w00; rr!=w18+19; rr+=3) *rr = *cs++;
  /* #111: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #112: @6 = ones(9x1,1nz) */
  w06 = 1.;
  /* #113: {NULL, @10} = vertsplit(@6) */
  w10 = w06;
  /* #114: @6 = @10[0] */
  for (rr=(&w06), cs=(&w10)+0; cs!=(&w10)+1; cs+=1) *rr++ = *cs;
  /* #115: @15 = (@15*@6) */
  w15 *= w06;
  /* #116: @7 = (@7*@15) */
  w07 *= w15;
  /* #117: @0 = vertcat(@7, @7, @7, @7, @7, @7) */
  rr=w00;
  *rr++ = w07;
  *rr++ = w07;
  *rr++ = w07;
  *rr++ = w07;
  *rr++ = w07;
  *rr++ = w07;
  /* #118: (@18[2:20:3] = @0) */
  for (rr=w18+2, cs=w00; rr!=w18+20; rr+=3) *rr = *cs++;
  /* #119: output[1][0] = @18 */
  casadi_copy(w18, 18, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int landing_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int landing_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int landing_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void landing_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int landing_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void landing_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void landing_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void landing_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int landing_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int landing_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real landing_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* landing_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* landing_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* landing_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* landing_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int landing_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 52;
  return 0;
}

CASADI_SYMBOL_EXPORT int landing_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 52*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
