/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) landing_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[27] = 
  {9, 6, 0, 3, 6, 9, 12, 15,
  18, 3, 4, 5, 3, 4, 5, 3,
  4, 5, 3, 4, 5, 3, 4, 5,
  3, 4, 5};
static const casadi_int casadi_s4[3] = {6, 0, 1};

/* landing_constr_h_fun_jac_uxt_zt:(i0[6],i1[3],i2[0],i3[0])->(o0[6],o1[9x6,18nz],o2[6x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w00=w+0, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, *w17=w+22, *w18=w+40, *w19=w+47;
  const casadi_real *cs;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 6, w00);
  /* #1: @1 = @0[0] */
  for (rr=(&w01), cs=w00+0; cs!=w00+1; cs+=1) *rr++ = *cs;
  /* #2: @2 = 400 */
  w02 = 400.;
  /* #3: @2 = (@1-@2) */
  w02  = (w01-w02);
  /* #4: @3 = 10 */
  w03 = 10.;
  /* #5: @2 = (@2/@3) */
  w02 /= w03;
  /* #6: @4 = sq(@2) */
  w04 = casadi_sq( w02 );
  /* #7: @5 = @0[1] */
  for (rr=(&w05), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #8: @6 = 2.5 */
  w06 = 2.5000000000000000e+00;
  /* #9: @6 = (@5-@6) */
  w06  = (w05-w06);
  /* #10: @6 = (@6/@3) */
  w06 /= w03;
  /* #11: @7 = sq(@6) */
  w07 = casadi_sq( w06 );
  /* #12: @4 = (@4+@7) */
  w04 += w07;
  /* #13: @7 = @0[2] */
  for (rr=(&w07), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #14: @7 = (@7/@3) */
  w07 /= w03;
  /* #15: @8 = sq(@7) */
  w08 = casadi_sq( w07 );
  /* #16: @4 = (@4+@8) */
  w04 += w08;
  /* #17: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #18: @4 = 600 */
  w04 = 600.;
  /* #19: @4 = (@1-@4) */
  w04  = (w01-w04);
  /* #20: @4 = (@4/@3) */
  w04 /= w03;
  /* #21: @9 = sq(@4) */
  w09 = casadi_sq( w04 );
  /* #22: @10 = -3 */
  w10 = -3.;
  /* #23: @10 = (@5-@10) */
  w10  = (w05-w10);
  /* #24: @10 = (@10/@3) */
  w10 /= w03;
  /* #25: @11 = sq(@10) */
  w11 = casadi_sq( w10 );
  /* #26: @9 = (@9+@11) */
  w09 += w11;
  /* #27: @9 = (@9+@8) */
  w09 += w08;
  /* #28: output[0][1] = @9 */
  if (res[0]) res[0][1] = w09;
  /* #29: @9 = 500 */
  w09 = 500.;
  /* #30: @9 = (@1-@9) */
  w09  = (w01-w09);
  /* #31: @9 = (@9/@3) */
  w09 /= w03;
  /* #32: @12 = sq(@9) */
  w12 = casadi_sq( w09 );
  /* #33: @13 = 12 */
  w13 = 12.;
  /* #34: @13 = (@5-@13) */
  w13  = (w05-w13);
  /* #35: @13 = (@13/@3) */
  w13 /= w03;
  /* #36: @14 = sq(@13) */
  w14 = casadi_sq( w13 );
  /* #37: @14 = (@12+@14) */
  w14  = (w12+w14);
  /* #38: @14 = (@14+@8) */
  w14 += w08;
  /* #39: output[0][2] = @14 */
  if (res[0]) res[0][2] = w14;
  /* #40: @14 = 200 */
  w14 = 200.;
  /* #41: @14 = (@1-@14) */
  w14  = (w01-w14);
  /* #42: @14 = (@14/@3) */
  w14 /= w03;
  /* #43: @15 = sq(@14) */
  w15 = casadi_sq( w14 );
  /* #44: @16 = 6 */
  w16 = 6.;
  /* #45: @5 = (@5-@16) */
  w05 -= w16;
  /* #46: @5 = (@5/@3) */
  w05 /= w03;
  /* #47: @16 = sq(@5) */
  w16 = casadi_sq( w05 );
  /* #48: @15 = (@15+@16) */
  w15 += w16;
  /* #49: @15 = (@15+@8) */
  w15 += w08;
  /* #50: output[0][3] = @15 */
  if (res[0]) res[0][3] = w15;
  /* #51: @15 = 100 */
  w15 = 100.;
  /* #52: @1 = (@1-@15) */
  w01 -= w15;
  /* #53: @1 = (@1/@3) */
  w01 /= w03;
  /* #54: @3 = sq(@1) */
  w03 = casadi_sq( w01 );
  /* #55: @3 = (@3+@11) */
  w03 += w11;
  /* #56: @3 = (@3+@8) */
  w03 += w08;
  /* #57: output[0][4] = @3 */
  if (res[0]) res[0][4] = w03;
  /* #58: @12 = (@12+@11) */
  w12 += w11;
  /* #59: @12 = (@12+@8) */
  w12 += w08;
  /* #60: output[0][5] = @12 */
  if (res[0]) res[0][5] = w12;
  /* #61: @17 = zeros(9x6,18nz) */
  casadi_clear(w17, 18);
  /* #62: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #63: @12 = 0.1 */
  w12 = 1.0000000000000001e-01;
  /* #64: @18 = ones(9x1,7nz) */
  casadi_fill(w18, 7, 1.);
  /* #65: {NULL, @19} = vertsplit(@18) */
  casadi_copy(w18+3, 4, w19);
  /* #66: @8 = @19[0] */
  for (rr=(&w08), cs=w19+0; cs!=w19+1; cs+=1) *rr++ = *cs;
  /* #67: @8 = (@12*@8) */
  w08  = (w12*w08);
  /* #68: @2 = (@2*@8) */
  w02 *= w08;
  /* #69: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #70: @4 = (@4*@8) */
  w04 *= w08;
  /* #71: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #72: @9 = (@9*@8) */
  w09 *= w08;
  /* #73: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #74: @14 = (@14*@8) */
  w14 *= w08;
  /* #75: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #76: @1 = (@1*@8) */
  w01 *= w08;
  /* #77: @0 = vertcat(@2, @4, @9, @14, @1, @9) */
  rr=w00;
  *rr++ = w02;
  *rr++ = w04;
  *rr++ = w09;
  *rr++ = w14;
  *rr++ = w01;
  *rr++ = w09;
  /* #78: (@17[:18:3] = @0) */
  for (rr=w17+0, cs=w00; rr!=w17+18; rr+=3) *rr = *cs++;
  /* #79: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #80: @2 = ones(9x1,1nz) */
  w02 = 1.;
  /* #81: {NULL, @4} = vertsplit(@2) */
  w04 = w02;
  /* #82: @2 = @4[0] */
  for (rr=(&w02), cs=(&w04)+0; cs!=(&w04)+1; cs+=1) *rr++ = *cs;
  /* #83: @2 = (@12*@2) */
  w02  = (w12*w02);
  /* #84: @6 = (@6*@2) */
  w06 *= w02;
  /* #85: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #86: @10 = (@10*@2) */
  w10 *= w02;
  /* #87: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #88: @13 = (@13*@2) */
  w13 *= w02;
  /* #89: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #90: @5 = (@5*@2) */
  w05 *= w02;
  /* #91: @0 = vertcat(@6, @10, @13, @5, @10, @10) */
  rr=w00;
  *rr++ = w06;
  *rr++ = w10;
  *rr++ = w13;
  *rr++ = w05;
  *rr++ = w10;
  *rr++ = w10;
  /* #92: (@17[1:19:3] = @0) */
  for (rr=w17+1, cs=w00; rr!=w17+19; rr+=3) *rr = *cs++;
  /* #93: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #94: @6 = ones(9x1,1nz) */
  w06 = 1.;
  /* #95: {NULL, @10} = vertsplit(@6) */
  w10 = w06;
  /* #96: @6 = @10[0] */
  for (rr=(&w06), cs=(&w10)+0; cs!=(&w10)+1; cs+=1) *rr++ = *cs;
  /* #97: @12 = (@12*@6) */
  w12 *= w06;
  /* #98: @7 = (@7*@12) */
  w07 *= w12;
  /* #99: @0 = vertcat(@7, @7, @7, @7, @7, @7) */
  rr=w00;
  *rr++ = w07;
  *rr++ = w07;
  *rr++ = w07;
  *rr++ = w07;
  *rr++ = w07;
  *rr++ = w07;
  /* #100: (@17[2:20:3] = @0) */
  for (rr=w17+2, cs=w00; rr!=w17+20; rr+=3) *rr = *cs++;
  /* #101: output[1][0] = @17 */
  casadi_copy(w17, 18, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int landing_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int landing_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int landing_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void landing_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int landing_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void landing_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void landing_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void landing_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int landing_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int landing_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real landing_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* landing_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* landing_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* landing_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* landing_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int landing_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 51;
  return 0;
}

CASADI_SYMBOL_EXPORT int landing_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 51*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
