/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) landing2_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[3] = {0, 1, 3};
static const casadi_int casadi_s1[14] = 
  {3, 6, 0, 0, 0, 0, 1, 3,
  5, 0, 1, 2, 1, 2};
static const casadi_int casadi_s2[11] = 
  {6, 3, 0, 1, 3, 5, 3, 4,
  5, 4, 5};
static const casadi_int casadi_s3[3] = {6, 1, 1};
static const casadi_int casadi_s4[3] = {6, 6, 1};
static const casadi_int casadi_s5[3] = {6, 3, 1};
static const casadi_int casadi_s6[3] = {3, 1, 1};
static const casadi_int casadi_s7[3] = {36, 1, 1};

static const casadi_real casadi_zeros[36] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* landing2_expl_vde_forw:(i0[6],i1[6x6],i2[6x3],i3[3],i4[36])->(o0[6],o1[6x6],o2[6x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+0, w01, w02, w03, w04, w05, w06, w07, w08, *w09=w+14, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, *w21=w+73, *w22=w+79, *w23=w+85, w24, w25;
  casadi_real w26, w27, w28, w29, w30, *w31=w+98, *w33=w+103, *w34=w+106, *w35=w+108, *w36=w+110, *w37=w+115, *w38=w+133;
  const casadi_int *cii;
  const casadi_real *cs, *wr00, *wr18, *wr19, *wr20, *wr21, *wr22, *wr23, *wr38;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 6, w00);
  /* #1: @1 = @0[3] */
  for (rr=(&w01), cs=w00+3; cs!=w00+4; cs+=1) *rr++ = *cs;
  /* #2: @2 = @0[4] */
  for (rr=(&w02), cs=w00+4; cs!=w00+5; cs+=1) *rr++ = *cs;
  /* #3: @3 = cos(@2) */
  w03 = cos( w02 );
  /* #4: @4 = (@1*@3) */
  w04  = (w01*w03);
  /* #5: @5 = @0[5] */
  for (rr=(&w05), cs=w00+5; cs!=w00+6; cs+=1) *rr++ = *cs;
  /* #6: @6 = cos(@5) */
  w06 = cos( w05 );
  /* #7: @7 = (@4*@6) */
  w07  = (w04*w06);
  /* #8: output[0][0] = @7 */
  if (res[0]) res[0][0] = w07;
  /* #9: @2 = sin(@2) */
  w02 = sin( w02 );
  /* #10: @7 = (@1*@2) */
  w07  = (w01*w02);
  /* #11: @8 = (@7*@6) */
  w08  = (w07*w06);
  /* #12: output[0][1] = @8 */
  if (res[0]) res[0][1] = w08;
  /* #13: @5 = sin(@5) */
  w05 = sin( w05 );
  /* #14: @8 = (@1*@5) */
  w08  = (w01*w05);
  /* #15: output[0][2] = @8 */
  if (res[0]) res[0][2] = w08;
  /* #16: @8 = 9.81 */
  w08 = 9.8100000000000005e+00;
  /* #17: @9 = input[3][0] */
  casadi_copy(arg[3], 3, w09);
  /* #18: @10 = @9[0] */
  for (rr=(&w10), cs=w09+0; cs!=w09+1; cs+=1) *rr++ = *cs;
  /* #19: @10 = (@10-@5) */
  w10 -= w05;
  /* #20: @10 = (@8*@10) */
  w10  = (w08*w10);
  /* #21: output[0][3] = @10 */
  if (res[0]) res[0][3] = w10;
  /* #22: @10 = @9[1] */
  for (rr=(&w10), cs=w09+1; cs!=w09+2; cs+=1) *rr++ = *cs;
  /* #23: @11 = (@8*@10) */
  w11  = (w08*w10);
  /* #24: @11 = (@11/@1) */
  w11 /= w01;
  /* #25: @12 = @9[2] */
  for (rr=(&w12), cs=w09+2; cs!=w09+3; cs+=1) *rr++ = *cs;
  /* #26: @13 = sin(@12) */
  w13 = sin( w12 );
  /* #27: @14 = (@11*@13) */
  w14  = (w11*w13);
  /* #28: @14 = (@14/@6) */
  w14 /= w06;
  /* #29: output[0][4] = @14 */
  if (res[0]) res[0][4] = w14;
  /* #30: @15 = (@8/@1) */
  w15  = (w08/w01);
  /* #31: @12 = cos(@12) */
  w12 = cos( w12 );
  /* #32: @16 = (@10*@12) */
  w16  = (w10*w12);
  /* #33: @16 = (@16-@6) */
  w16 -= w06;
  /* #34: @17 = (@15*@16) */
  w17  = (w15*w16);
  /* #35: output[0][5] = @17 */
  if (res[0]) res[0][5] = w17;
  /* #36: @18 = input[1][0] */
  wr18 = arg[1] ? arg[1] : casadi_zeros;
  /* #37: {@0, @19, @20, @21, @22, @23} = horzsplit(@18) */
  wr00 = wr18;
  wr19 = wr18+6;
  wr20 = wr18+12;
  wr21 = wr18+18;
  wr22 = wr18+24;
  wr23 = wr18+30;
  /* #38: @17 = @0[3] */
  w17 = wr00[3];
  /* #39: @24 = (@3*@17) */
  w24  = (w03*w17);
  /* #40: @25 = @0[4] */
  w25 = wr00[4];
  /* #41: @26 = (@2*@25) */
  w26  = (w02*w25);
  /* #42: @26 = (@1*@26) */
  w26  = (w01*w26);
  /* #43: @24 = (@24-@26) */
  w24 -= w26;
  /* #44: @24 = (@6*@24) */
  w24  = (w06*w24);
  /* #45: @26 = @0[5] */
  w26 = wr00[5];
  /* #46: @27 = (@5*@26) */
  w27  = (w05*w26);
  /* #47: @28 = (@4*@27) */
  w28  = (w04*w27);
  /* #48: @24 = (@24-@28) */
  w24 -= w28;
  /* #49: output[1][0] = @24 */
  if (res[1]) res[1][0] = w24;
  /* #50: @24 = (@2*@17) */
  w24  = (w02*w17);
  /* #51: @25 = (@3*@25) */
  w25  = (w03*w25);
  /* #52: @25 = (@1*@25) */
  w25  = (w01*w25);
  /* #53: @24 = (@24+@25) */
  w24 += w25;
  /* #54: @24 = (@6*@24) */
  w24  = (w06*w24);
  /* #55: @25 = (@7*@27) */
  w25  = (w07*w27);
  /* #56: @24 = (@24-@25) */
  w24 -= w25;
  /* #57: output[1][1] = @24 */
  if (res[1]) res[1][1] = w24;
  /* #58: @24 = (@5*@17) */
  w24  = (w05*w17);
  /* #59: @26 = (@6*@26) */
  w26  = (w06*w26);
  /* #60: @25 = (@1*@26) */
  w25  = (w01*w26);
  /* #61: @24 = (@24+@25) */
  w24 += w25;
  /* #62: output[1][2] = @24 */
  if (res[1]) res[1][2] = w24;
  /* #63: @26 = (@8*@26) */
  w26  = (w08*w26);
  /* #64: @26 = (-@26) */
  w26 = (- w26 );
  /* #65: output[1][3] = @26 */
  if (res[1]) res[1][3] = w26;
  /* #66: @14 = (@14/@6) */
  w14 /= w06;
  /* #67: @26 = (@14*@27) */
  w26  = (w14*w27);
  /* #68: @24 = (@11/@1) */
  w24  = (w11/w01);
  /* #69: @25 = (@24*@17) */
  w25  = (w24*w17);
  /* #70: @25 = (@13*@25) */
  w25  = (w13*w25);
  /* #71: @25 = (@25/@6) */
  w25 /= w06;
  /* #72: @26 = (@26-@25) */
  w26 -= w25;
  /* #73: output[1][4] = @26 */
  if (res[1]) res[1][4] = w26;
  /* #74: @27 = (@15*@27) */
  w27  = (w15*w27);
  /* #75: @26 = (@15/@1) */
  w26  = (w15/w01);
  /* #76: @17 = (@26*@17) */
  w17  = (w26*w17);
  /* #77: @17 = (@16*@17) */
  w17  = (w16*w17);
  /* #78: @27 = (@27-@17) */
  w27 -= w17;
  /* #79: output[1][5] = @27 */
  if (res[1]) res[1][5] = w27;
  /* #80: @27 = @19[3] */
  w27 = wr19[3];
  /* #81: @17 = (@3*@27) */
  w17  = (w03*w27);
  /* #82: @25 = @19[4] */
  w25 = wr19[4];
  /* #83: @28 = (@2*@25) */
  w28  = (w02*w25);
  /* #84: @28 = (@1*@28) */
  w28  = (w01*w28);
  /* #85: @17 = (@17-@28) */
  w17 -= w28;
  /* #86: @17 = (@6*@17) */
  w17  = (w06*w17);
  /* #87: @28 = @19[5] */
  w28 = wr19[5];
  /* #88: @29 = (@5*@28) */
  w29  = (w05*w28);
  /* #89: @30 = (@4*@29) */
  w30  = (w04*w29);
  /* #90: @17 = (@17-@30) */
  w17 -= w30;
  /* #91: output[1][6] = @17 */
  if (res[1]) res[1][6] = w17;
  /* #92: @17 = (@2*@27) */
  w17  = (w02*w27);
  /* #93: @25 = (@3*@25) */
  w25  = (w03*w25);
  /* #94: @25 = (@1*@25) */
  w25  = (w01*w25);
  /* #95: @17 = (@17+@25) */
  w17 += w25;
  /* #96: @17 = (@6*@17) */
  w17  = (w06*w17);
  /* #97: @25 = (@7*@29) */
  w25  = (w07*w29);
  /* #98: @17 = (@17-@25) */
  w17 -= w25;
  /* #99: output[1][7] = @17 */
  if (res[1]) res[1][7] = w17;
  /* #100: @17 = (@5*@27) */
  w17  = (w05*w27);
  /* #101: @28 = (@6*@28) */
  w28  = (w06*w28);
  /* #102: @25 = (@1*@28) */
  w25  = (w01*w28);
  /* #103: @17 = (@17+@25) */
  w17 += w25;
  /* #104: output[1][8] = @17 */
  if (res[1]) res[1][8] = w17;
  /* #105: @28 = (@8*@28) */
  w28  = (w08*w28);
  /* #106: @28 = (-@28) */
  w28 = (- w28 );
  /* #107: output[1][9] = @28 */
  if (res[1]) res[1][9] = w28;
  /* #108: @28 = (@14*@29) */
  w28  = (w14*w29);
  /* #109: @17 = (@24*@27) */
  w17  = (w24*w27);
  /* #110: @17 = (@13*@17) */
  w17  = (w13*w17);
  /* #111: @17 = (@17/@6) */
  w17 /= w06;
  /* #112: @28 = (@28-@17) */
  w28 -= w17;
  /* #113: output[1][10] = @28 */
  if (res[1]) res[1][10] = w28;
  /* #114: @29 = (@15*@29) */
  w29  = (w15*w29);
  /* #115: @27 = (@26*@27) */
  w27  = (w26*w27);
  /* #116: @27 = (@16*@27) */
  w27  = (w16*w27);
  /* #117: @29 = (@29-@27) */
  w29 -= w27;
  /* #118: output[1][11] = @29 */
  if (res[1]) res[1][11] = w29;
  /* #119: @29 = @20[3] */
  w29 = wr20[3];
  /* #120: @27 = (@3*@29) */
  w27  = (w03*w29);
  /* #121: @28 = @20[4] */
  w28 = wr20[4];
  /* #122: @17 = (@2*@28) */
  w17  = (w02*w28);
  /* #123: @17 = (@1*@17) */
  w17  = (w01*w17);
  /* #124: @27 = (@27-@17) */
  w27 -= w17;
  /* #125: @27 = (@6*@27) */
  w27  = (w06*w27);
  /* #126: @17 = @20[5] */
  w17 = wr20[5];
  /* #127: @25 = (@5*@17) */
  w25  = (w05*w17);
  /* #128: @30 = (@4*@25) */
  w30  = (w04*w25);
  /* #129: @27 = (@27-@30) */
  w27 -= w30;
  /* #130: output[1][12] = @27 */
  if (res[1]) res[1][12] = w27;
  /* #131: @27 = (@2*@29) */
  w27  = (w02*w29);
  /* #132: @28 = (@3*@28) */
  w28  = (w03*w28);
  /* #133: @28 = (@1*@28) */
  w28  = (w01*w28);
  /* #134: @27 = (@27+@28) */
  w27 += w28;
  /* #135: @27 = (@6*@27) */
  w27  = (w06*w27);
  /* #136: @28 = (@7*@25) */
  w28  = (w07*w25);
  /* #137: @27 = (@27-@28) */
  w27 -= w28;
  /* #138: output[1][13] = @27 */
  if (res[1]) res[1][13] = w27;
  /* #139: @27 = (@5*@29) */
  w27  = (w05*w29);
  /* #140: @17 = (@6*@17) */
  w17  = (w06*w17);
  /* #141: @28 = (@1*@17) */
  w28  = (w01*w17);
  /* #142: @27 = (@27+@28) */
  w27 += w28;
  /* #143: output[1][14] = @27 */
  if (res[1]) res[1][14] = w27;
  /* #144: @17 = (@8*@17) */
  w17  = (w08*w17);
  /* #145: @17 = (-@17) */
  w17 = (- w17 );
  /* #146: output[1][15] = @17 */
  if (res[1]) res[1][15] = w17;
  /* #147: @17 = (@14*@25) */
  w17  = (w14*w25);
  /* #148: @27 = (@24*@29) */
  w27  = (w24*w29);
  /* #149: @27 = (@13*@27) */
  w27  = (w13*w27);
  /* #150: @27 = (@27/@6) */
  w27 /= w06;
  /* #151: @17 = (@17-@27) */
  w17 -= w27;
  /* #152: output[1][16] = @17 */
  if (res[1]) res[1][16] = w17;
  /* #153: @25 = (@15*@25) */
  w25  = (w15*w25);
  /* #154: @29 = (@26*@29) */
  w29  = (w26*w29);
  /* #155: @29 = (@16*@29) */
  w29  = (w16*w29);
  /* #156: @25 = (@25-@29) */
  w25 -= w29;
  /* #157: output[1][17] = @25 */
  if (res[1]) res[1][17] = w25;
  /* #158: @25 = @21[3] */
  w25 = wr21[3];
  /* #159: @29 = (@3*@25) */
  w29  = (w03*w25);
  /* #160: @17 = @21[4] */
  w17 = wr21[4];
  /* #161: @27 = (@2*@17) */
  w27  = (w02*w17);
  /* #162: @27 = (@1*@27) */
  w27  = (w01*w27);
  /* #163: @29 = (@29-@27) */
  w29 -= w27;
  /* #164: @29 = (@6*@29) */
  w29  = (w06*w29);
  /* #165: @27 = @21[5] */
  w27 = wr21[5];
  /* #166: @28 = (@5*@27) */
  w28  = (w05*w27);
  /* #167: @30 = (@4*@28) */
  w30  = (w04*w28);
  /* #168: @29 = (@29-@30) */
  w29 -= w30;
  /* #169: output[1][18] = @29 */
  if (res[1]) res[1][18] = w29;
  /* #170: @29 = (@2*@25) */
  w29  = (w02*w25);
  /* #171: @17 = (@3*@17) */
  w17  = (w03*w17);
  /* #172: @17 = (@1*@17) */
  w17  = (w01*w17);
  /* #173: @29 = (@29+@17) */
  w29 += w17;
  /* #174: @29 = (@6*@29) */
  w29  = (w06*w29);
  /* #175: @17 = (@7*@28) */
  w17  = (w07*w28);
  /* #176: @29 = (@29-@17) */
  w29 -= w17;
  /* #177: output[1][19] = @29 */
  if (res[1]) res[1][19] = w29;
  /* #178: @29 = (@5*@25) */
  w29  = (w05*w25);
  /* #179: @27 = (@6*@27) */
  w27  = (w06*w27);
  /* #180: @17 = (@1*@27) */
  w17  = (w01*w27);
  /* #181: @29 = (@29+@17) */
  w29 += w17;
  /* #182: output[1][20] = @29 */
  if (res[1]) res[1][20] = w29;
  /* #183: @27 = (@8*@27) */
  w27  = (w08*w27);
  /* #184: @27 = (-@27) */
  w27 = (- w27 );
  /* #185: output[1][21] = @27 */
  if (res[1]) res[1][21] = w27;
  /* #186: @27 = (@14*@28) */
  w27  = (w14*w28);
  /* #187: @29 = (@24*@25) */
  w29  = (w24*w25);
  /* #188: @29 = (@13*@29) */
  w29  = (w13*w29);
  /* #189: @29 = (@29/@6) */
  w29 /= w06;
  /* #190: @27 = (@27-@29) */
  w27 -= w29;
  /* #191: output[1][22] = @27 */
  if (res[1]) res[1][22] = w27;
  /* #192: @28 = (@15*@28) */
  w28  = (w15*w28);
  /* #193: @25 = (@26*@25) */
  w25  = (w26*w25);
  /* #194: @25 = (@16*@25) */
  w25  = (w16*w25);
  /* #195: @28 = (@28-@25) */
  w28 -= w25;
  /* #196: output[1][23] = @28 */
  if (res[1]) res[1][23] = w28;
  /* #197: @28 = @22[3] */
  w28 = wr22[3];
  /* #198: @25 = (@3*@28) */
  w25  = (w03*w28);
  /* #199: @27 = @22[4] */
  w27 = wr22[4];
  /* #200: @29 = (@2*@27) */
  w29  = (w02*w27);
  /* #201: @29 = (@1*@29) */
  w29  = (w01*w29);
  /* #202: @25 = (@25-@29) */
  w25 -= w29;
  /* #203: @25 = (@6*@25) */
  w25  = (w06*w25);
  /* #204: @29 = @22[5] */
  w29 = wr22[5];
  /* #205: @17 = (@5*@29) */
  w17  = (w05*w29);
  /* #206: @30 = (@4*@17) */
  w30  = (w04*w17);
  /* #207: @25 = (@25-@30) */
  w25 -= w30;
  /* #208: output[1][24] = @25 */
  if (res[1]) res[1][24] = w25;
  /* #209: @25 = (@2*@28) */
  w25  = (w02*w28);
  /* #210: @27 = (@3*@27) */
  w27  = (w03*w27);
  /* #211: @27 = (@1*@27) */
  w27  = (w01*w27);
  /* #212: @25 = (@25+@27) */
  w25 += w27;
  /* #213: @25 = (@6*@25) */
  w25  = (w06*w25);
  /* #214: @27 = (@7*@17) */
  w27  = (w07*w17);
  /* #215: @25 = (@25-@27) */
  w25 -= w27;
  /* #216: output[1][25] = @25 */
  if (res[1]) res[1][25] = w25;
  /* #217: @25 = (@5*@28) */
  w25  = (w05*w28);
  /* #218: @29 = (@6*@29) */
  w29  = (w06*w29);
  /* #219: @27 = (@1*@29) */
  w27  = (w01*w29);
  /* #220: @25 = (@25+@27) */
  w25 += w27;
  /* #221: output[1][26] = @25 */
  if (res[1]) res[1][26] = w25;
  /* #222: @29 = (@8*@29) */
  w29  = (w08*w29);
  /* #223: @29 = (-@29) */
  w29 = (- w29 );
  /* #224: output[1][27] = @29 */
  if (res[1]) res[1][27] = w29;
  /* #225: @29 = (@14*@17) */
  w29  = (w14*w17);
  /* #226: @25 = (@24*@28) */
  w25  = (w24*w28);
  /* #227: @25 = (@13*@25) */
  w25  = (w13*w25);
  /* #228: @25 = (@25/@6) */
  w25 /= w06;
  /* #229: @29 = (@29-@25) */
  w29 -= w25;
  /* #230: output[1][28] = @29 */
  if (res[1]) res[1][28] = w29;
  /* #231: @17 = (@15*@17) */
  w17  = (w15*w17);
  /* #232: @28 = (@26*@28) */
  w28  = (w26*w28);
  /* #233: @28 = (@16*@28) */
  w28  = (w16*w28);
  /* #234: @17 = (@17-@28) */
  w17 -= w28;
  /* #235: output[1][29] = @17 */
  if (res[1]) res[1][29] = w17;
  /* #236: @17 = @23[3] */
  w17 = wr23[3];
  /* #237: @28 = (@3*@17) */
  w28  = (w03*w17);
  /* #238: @29 = @23[4] */
  w29 = wr23[4];
  /* #239: @25 = (@2*@29) */
  w25  = (w02*w29);
  /* #240: @25 = (@1*@25) */
  w25  = (w01*w25);
  /* #241: @28 = (@28-@25) */
  w28 -= w25;
  /* #242: @28 = (@6*@28) */
  w28  = (w06*w28);
  /* #243: @25 = @23[5] */
  w25 = wr23[5];
  /* #244: @27 = (@5*@25) */
  w27  = (w05*w25);
  /* #245: @30 = (@4*@27) */
  w30  = (w04*w27);
  /* #246: @28 = (@28-@30) */
  w28 -= w30;
  /* #247: output[1][30] = @28 */
  if (res[1]) res[1][30] = w28;
  /* #248: @28 = (@2*@17) */
  w28  = (w02*w17);
  /* #249: @29 = (@3*@29) */
  w29  = (w03*w29);
  /* #250: @29 = (@1*@29) */
  w29  = (w01*w29);
  /* #251: @28 = (@28+@29) */
  w28 += w29;
  /* #252: @28 = (@6*@28) */
  w28  = (w06*w28);
  /* #253: @29 = (@7*@27) */
  w29  = (w07*w27);
  /* #254: @28 = (@28-@29) */
  w28 -= w29;
  /* #255: output[1][31] = @28 */
  if (res[1]) res[1][31] = w28;
  /* #256: @28 = (@5*@17) */
  w28  = (w05*w17);
  /* #257: @25 = (@6*@25) */
  w25  = (w06*w25);
  /* #258: @29 = (@1*@25) */
  w29  = (w01*w25);
  /* #259: @28 = (@28+@29) */
  w28 += w29;
  /* #260: output[1][32] = @28 */
  if (res[1]) res[1][32] = w28;
  /* #261: @25 = (@8*@25) */
  w25  = (w08*w25);
  /* #262: @25 = (-@25) */
  w25 = (- w25 );
  /* #263: output[1][33] = @25 */
  if (res[1]) res[1][33] = w25;
  /* #264: @25 = (@14*@27) */
  w25  = (w14*w27);
  /* #265: @28 = (@24*@17) */
  w28  = (w24*w17);
  /* #266: @28 = (@13*@28) */
  w28  = (w13*w28);
  /* #267: @28 = (@28/@6) */
  w28 /= w06;
  /* #268: @25 = (@25-@28) */
  w25 -= w28;
  /* #269: output[1][34] = @25 */
  if (res[1]) res[1][34] = w25;
  /* #270: @27 = (@15*@27) */
  w27  = (w15*w27);
  /* #271: @17 = (@26*@17) */
  w17  = (w26*w17);
  /* #272: @17 = (@16*@17) */
  w17  = (w16*w17);
  /* #273: @27 = (@27-@17) */
  w27 -= w17;
  /* #274: output[1][35] = @27 */
  if (res[1]) res[1][35] = w27;
  /* #275: @31 = zeros(3x6,5nz) */
  casadi_clear(w31, 5);
  /* #276: @32 = 00 */
  /* #277: @27 = (@13*@15) */
  w27  = (w13*w15);
  /* #278: @27 = (@27/@6) */
  w27 /= w06;
  /* #279: @17 = (@15*@12) */
  w17  = (w15*w12);
  /* #280: @9 = vertcat(@32, @32, @32, @8, @27, @17) */
  rr=w09;
  *rr++ = w08;
  *rr++ = w27;
  *rr++ = w17;
  /* #281: @33 = @9[:3] */
  for (rr=w33, cs=w09+0; cs!=w09+3; cs+=1) *rr++ = *cs;
  /* #282: (@31[0, 1, 3] = @33) */
  for (cii=casadi_s0, rr=w31, cs=w33; cii!=casadi_s0+3; ++cii, ++cs) rr[*cii] = *cs;
  /* #283: @11 = (@11*@12) */
  w11 *= w12;
  /* #284: @11 = (@11/@6) */
  w11 /= w06;
  /* #285: @10 = (@10*@13) */
  w10 *= w13;
  /* #286: @10 = (@15*@10) */
  w10  = (w15*w10);
  /* #287: @10 = (-@10) */
  w10 = (- w10 );
  /* #288: @34 = vertcat(@32, @32, @32, @32, @11, @10) */
  rr=w34;
  *rr++ = w11;
  *rr++ = w10;
  /* #289: @35 = @34[:2] */
  for (rr=w35, cs=w34+0; cs!=w34+2; cs+=1) *rr++ = *cs;
  /* #290: (@31[2:6:2] = @35) */
  for (rr=w31+2, cs=w35; rr!=w31+6; rr+=2) *rr = *cs++;
  /* #291: @36 = @31' */
  casadi_trans(w31,casadi_s1, w36, casadi_s2, iw);
  /* #292: @37 = dense(@36) */
  casadi_densify(w36, casadi_s2, w37, 0);
  /* #293: @38 = input[2][0] */
  wr38 = arg[2] ? arg[2] : casadi_zeros;
  /* #294: {@23, @22, @21} = horzsplit(@38) */
  wr23 = wr38;
  wr22 = wr38+6;
  wr21 = wr38+12;
  /* #295: @11 = @23[3] */
  w11 = wr23[3];
  /* #296: @10 = (@3*@11) */
  w10  = (w03*w11);
  /* #297: @12 = @23[4] */
  w12 = wr23[4];
  /* #298: @27 = (@2*@12) */
  w27  = (w02*w12);
  /* #299: @27 = (@1*@27) */
  w27  = (w01*w27);
  /* #300: @10 = (@10-@27) */
  w10 -= w27;
  /* #301: @10 = (@6*@10) */
  w10  = (w06*w10);
  /* #302: @27 = @23[5] */
  w27 = wr23[5];
  /* #303: @17 = (@5*@27) */
  w17  = (w05*w27);
  /* #304: @25 = (@4*@17) */
  w25  = (w04*w17);
  /* #305: @10 = (@10-@25) */
  w10 -= w25;
  /* #306: @25 = (@2*@11) */
  w25  = (w02*w11);
  /* #307: @12 = (@3*@12) */
  w12  = (w03*w12);
  /* #308: @12 = (@1*@12) */
  w12  = (w01*w12);
  /* #309: @25 = (@25+@12) */
  w25 += w12;
  /* #310: @25 = (@6*@25) */
  w25  = (w06*w25);
  /* #311: @12 = (@7*@17) */
  w12  = (w07*w17);
  /* #312: @25 = (@25-@12) */
  w25 -= w12;
  /* #313: @12 = (@5*@11) */
  w12  = (w05*w11);
  /* #314: @27 = (@6*@27) */
  w27  = (w06*w27);
  /* #315: @28 = (@1*@27) */
  w28  = (w01*w27);
  /* #316: @12 = (@12+@28) */
  w12 += w28;
  /* #317: @27 = (@8*@27) */
  w27  = (w08*w27);
  /* #318: @27 = (-@27) */
  w27 = (- w27 );
  /* #319: @28 = (@14*@17) */
  w28  = (w14*w17);
  /* #320: @29 = (@24*@11) */
  w29  = (w24*w11);
  /* #321: @29 = (@13*@29) */
  w29  = (w13*w29);
  /* #322: @29 = (@29/@6) */
  w29 /= w06;
  /* #323: @28 = (@28-@29) */
  w28 -= w29;
  /* #324: @17 = (@15*@17) */
  w17  = (w15*w17);
  /* #325: @11 = (@26*@11) */
  w11  = (w26*w11);
  /* #326: @11 = (@16*@11) */
  w11  = (w16*w11);
  /* #327: @17 = (@17-@11) */
  w17 -= w11;
  /* #328: @23 = vertcat(@10, @25, @12, @27, @28, @17) */
  rr=w23;
  *rr++ = w10;
  *rr++ = w25;
  *rr++ = w12;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w17;
  /* #329: @10 = @22[3] */
  w10 = wr22[3];
  /* #330: @25 = (@3*@10) */
  w25  = (w03*w10);
  /* #331: @12 = @22[4] */
  w12 = wr22[4];
  /* #332: @27 = (@2*@12) */
  w27  = (w02*w12);
  /* #333: @27 = (@1*@27) */
  w27  = (w01*w27);
  /* #334: @25 = (@25-@27) */
  w25 -= w27;
  /* #335: @25 = (@6*@25) */
  w25  = (w06*w25);
  /* #336: @27 = @22[5] */
  w27 = wr22[5];
  /* #337: @28 = (@5*@27) */
  w28  = (w05*w27);
  /* #338: @17 = (@4*@28) */
  w17  = (w04*w28);
  /* #339: @25 = (@25-@17) */
  w25 -= w17;
  /* #340: @17 = (@2*@10) */
  w17  = (w02*w10);
  /* #341: @12 = (@3*@12) */
  w12  = (w03*w12);
  /* #342: @12 = (@1*@12) */
  w12  = (w01*w12);
  /* #343: @17 = (@17+@12) */
  w17 += w12;
  /* #344: @17 = (@6*@17) */
  w17  = (w06*w17);
  /* #345: @12 = (@7*@28) */
  w12  = (w07*w28);
  /* #346: @17 = (@17-@12) */
  w17 -= w12;
  /* #347: @12 = (@5*@10) */
  w12  = (w05*w10);
  /* #348: @27 = (@6*@27) */
  w27  = (w06*w27);
  /* #349: @11 = (@1*@27) */
  w11  = (w01*w27);
  /* #350: @12 = (@12+@11) */
  w12 += w11;
  /* #351: @27 = (@8*@27) */
  w27  = (w08*w27);
  /* #352: @27 = (-@27) */
  w27 = (- w27 );
  /* #353: @11 = (@14*@28) */
  w11  = (w14*w28);
  /* #354: @29 = (@24*@10) */
  w29  = (w24*w10);
  /* #355: @29 = (@13*@29) */
  w29  = (w13*w29);
  /* #356: @29 = (@29/@6) */
  w29 /= w06;
  /* #357: @11 = (@11-@29) */
  w11 -= w29;
  /* #358: @28 = (@15*@28) */
  w28  = (w15*w28);
  /* #359: @10 = (@26*@10) */
  w10  = (w26*w10);
  /* #360: @10 = (@16*@10) */
  w10  = (w16*w10);
  /* #361: @28 = (@28-@10) */
  w28 -= w10;
  /* #362: @22 = vertcat(@25, @17, @12, @27, @11, @28) */
  rr=w22;
  *rr++ = w25;
  *rr++ = w17;
  *rr++ = w12;
  *rr++ = w27;
  *rr++ = w11;
  *rr++ = w28;
  /* #363: @25 = @21[3] */
  w25 = wr21[3];
  /* #364: @17 = (@3*@25) */
  w17  = (w03*w25);
  /* #365: @12 = @21[4] */
  w12 = wr21[4];
  /* #366: @27 = (@2*@12) */
  w27  = (w02*w12);
  /* #367: @27 = (@1*@27) */
  w27  = (w01*w27);
  /* #368: @17 = (@17-@27) */
  w17 -= w27;
  /* #369: @17 = (@6*@17) */
  w17  = (w06*w17);
  /* #370: @27 = @21[5] */
  w27 = wr21[5];
  /* #371: @11 = (@5*@27) */
  w11  = (w05*w27);
  /* #372: @4 = (@4*@11) */
  w04 *= w11;
  /* #373: @17 = (@17-@4) */
  w17 -= w04;
  /* #374: @2 = (@2*@25) */
  w02 *= w25;
  /* #375: @3 = (@3*@12) */
  w03 *= w12;
  /* #376: @3 = (@1*@3) */
  w03  = (w01*w03);
  /* #377: @2 = (@2+@3) */
  w02 += w03;
  /* #378: @2 = (@6*@2) */
  w02  = (w06*w02);
  /* #379: @7 = (@7*@11) */
  w07 *= w11;
  /* #380: @2 = (@2-@7) */
  w02 -= w07;
  /* #381: @5 = (@5*@25) */
  w05 *= w25;
  /* #382: @27 = (@6*@27) */
  w27  = (w06*w27);
  /* #383: @1 = (@1*@27) */
  w01 *= w27;
  /* #384: @5 = (@5+@1) */
  w05 += w01;
  /* #385: @8 = (@8*@27) */
  w08 *= w27;
  /* #386: @8 = (-@8) */
  w08 = (- w08 );
  /* #387: @14 = (@14*@11) */
  w14 *= w11;
  /* #388: @24 = (@24*@25) */
  w24 *= w25;
  /* #389: @13 = (@13*@24) */
  w13 *= w24;
  /* #390: @13 = (@13/@6) */
  w13 /= w06;
  /* #391: @14 = (@14-@13) */
  w14 -= w13;
  /* #392: @15 = (@15*@11) */
  w15 *= w11;
  /* #393: @26 = (@26*@25) */
  w26 *= w25;
  /* #394: @16 = (@16*@26) */
  w16 *= w26;
  /* #395: @15 = (@15-@16) */
  w15 -= w16;
  /* #396: @21 = vertcat(@17, @2, @5, @8, @14, @15) */
  rr=w21;
  *rr++ = w17;
  *rr++ = w02;
  *rr++ = w05;
  *rr++ = w08;
  *rr++ = w14;
  *rr++ = w15;
  /* #397: @38 = horzcat(@23, @22, @21) */
  rr=w38;
  for (i=0, cs=w23; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<6; ++i) *rr++ = *cs++;
  /* #398: @37 = (@37+@38) */
  for (i=0, rr=w37, cs=w38; i<18; ++i) (*rr++) += (*cs++);
  /* #399: output[2][0] = @37 */
  casadi_copy(w37, 18, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int landing2_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int landing2_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int landing2_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void landing2_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int landing2_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void landing2_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void landing2_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void landing2_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int landing2_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int landing2_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real landing2_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* landing2_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* landing2_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* landing2_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    case 4: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* landing2_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int landing2_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 4;
  if (sz_w) *sz_w = 151;
  return 0;
}

CASADI_SYMBOL_EXPORT int landing2_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 4*sizeof(casadi_int);
  if (sz_w) *sz_w = 151*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
