/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) landing2_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {36, 1, 1};

/* landing2_expl_ode_fun:(i0[6],i1[3],i2[36])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w0=w+0, w1, w2, w3, w4, w5, *w6=w+11, w7, w8;
  const casadi_real *cs;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 6, w0);
  /* #1: @1 = @0[3] */
  for (rr=(&w1), cs=w0+3; cs!=w0+4; cs+=1) *rr++ = *cs;
  /* #2: @2 = @0[4] */
  for (rr=(&w2), cs=w0+4; cs!=w0+5; cs+=1) *rr++ = *cs;
  /* #3: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #4: @3 = (@1*@3) */
  w3  = (w1*w3);
  /* #5: @4 = @0[5] */
  for (rr=(&w4), cs=w0+5; cs!=w0+6; cs+=1) *rr++ = *cs;
  /* #6: @5 = cos(@4) */
  w5 = cos( w4 );
  /* #7: @3 = (@3*@5) */
  w3 *= w5;
  /* #8: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  /* #9: @2 = sin(@2) */
  w2 = sin( w2 );
  /* #10: @2 = (@1*@2) */
  w2  = (w1*w2);
  /* #11: @2 = (@2*@5) */
  w2 *= w5;
  /* #12: output[0][1] = @2 */
  if (res[0]) res[0][1] = w2;
  /* #13: @4 = sin(@4) */
  w4 = sin( w4 );
  /* #14: @2 = (@1*@4) */
  w2  = (w1*w4);
  /* #15: output[0][2] = @2 */
  if (res[0]) res[0][2] = w2;
  /* #16: @2 = 9.81 */
  w2 = 9.8100000000000005e+00;
  /* #17: @6 = input[1][0] */
  casadi_copy(arg[1], 3, w6);
  /* #18: @3 = @6[0] */
  for (rr=(&w3), cs=w6+0; cs!=w6+1; cs+=1) *rr++ = *cs;
  /* #19: @3 = (@3-@4) */
  w3 -= w4;
  /* #20: @3 = (@2*@3) */
  w3  = (w2*w3);
  /* #21: output[0][3] = @3 */
  if (res[0]) res[0][3] = w3;
  /* #22: @3 = @6[1] */
  for (rr=(&w3), cs=w6+1; cs!=w6+2; cs+=1) *rr++ = *cs;
  /* #23: @4 = (@2*@3) */
  w4  = (w2*w3);
  /* #24: @4 = (@4/@1) */
  w4 /= w1;
  /* #25: @7 = @6[2] */
  for (rr=(&w7), cs=w6+2; cs!=w6+3; cs+=1) *rr++ = *cs;
  /* #26: @8 = sin(@7) */
  w8 = sin( w7 );
  /* #27: @4 = (@4*@8) */
  w4 *= w8;
  /* #28: @4 = (@4/@5) */
  w4 /= w5;
  /* #29: output[0][4] = @4 */
  if (res[0]) res[0][4] = w4;
  /* #30: @2 = (@2/@1) */
  w2 /= w1;
  /* #31: @7 = cos(@7) */
  w7 = cos( w7 );
  /* #32: @3 = (@3*@7) */
  w3 *= w7;
  /* #33: @3 = (@3-@5) */
  w3 -= w5;
  /* #34: @2 = (@2*@3) */
  w2 *= w3;
  /* #35: output[0][5] = @2 */
  if (res[0]) res[0][5] = w2;
  return 0;
}

CASADI_SYMBOL_EXPORT int landing2_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int landing2_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int landing2_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void landing2_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int landing2_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void landing2_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void landing2_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void landing2_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int landing2_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int landing2_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real landing2_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* landing2_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* landing2_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* landing2_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* landing2_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int landing2_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 16;
  return 0;
}

CASADI_SYMBOL_EXPORT int landing2_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 16*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
