/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) landing2_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {36, 1, 1};
static const casadi_int casadi_s4[27] = 
  {9, 6, 0, 3, 6, 9, 12, 15,
  18, 3, 4, 5, 3, 4, 5, 3,
  4, 5, 3, 4, 5, 3, 4, 5,
  3, 4, 5};
static const casadi_int casadi_s5[3] = {6, 0, 1};

static const casadi_real casadi_zeros[36] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* landing2_constr_h_fun_jac_uxt_zt:(i0[6],i1[3],i2[0],i3[36])->(o0[6],o1[9x6,18nz],o2[6x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *w00=w+0, w01, *w04=w+61, w05, *w06=w+80, w07, w08, w09, w10, w11, w12;
  casadi_real w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24;
  casadi_real w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35, w36;
  casadi_real w37, w38, w39, w40, w41, w42, *w43=w+134, *w44=w+141;
  const casadi_real *cs, *wr02, *wr03;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 6, w00);
  /* #1: @1 = @0[0] */
  for (rr=(&w01), cs=w00+0; cs!=w00+1; cs+=1) *rr++ = *cs;
  /* #2: @2 = input[3][0] */
  wr02 = arg[3] ? arg[3] : casadi_zeros;
  /* #3: @3 = @2[:18] */
  wr03 = wr02+0;
  /* #4: @3 = reshape(@3) */
  /* #5: @4 = @3' */
  for (i=0, rr=w04, cs=wr03; i<6; ++i) for (j=0; j<3; ++j) rr[i+j*6] = *cs++;
  /* #6: @5 = @4[0] */
  for (rr=(&w05), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #7: @5 = (@1-@5) */
  w05  = (w01-w05);
  /* #8: @3 = @2[18:36] */
  wr03 = wr02+18;
  /* #9: @3 = reshape(@3) */
  /* #10: @6 = @3' */
  for (i=0, rr=w06, cs=wr03; i<6; ++i) for (j=0; j<3; ++j) rr[i+j*6] = *cs++;
  /* #11: @7 = @6[0] */
  for (rr=(&w07), cs=w06+0; cs!=w06+1; cs+=1) *rr++ = *cs;
  /* #12: @5 = (@5/@7) */
  w05 /= w07;
  /* #13: @8 = sq(@5) */
  w08 = casadi_sq( w05 );
  /* #14: @9 = @0[1] */
  for (rr=(&w09), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #15: @10 = @4[6] */
  for (rr=(&w10), cs=w04+6; cs!=w04+7; cs+=1) *rr++ = *cs;
  /* #16: @10 = (@9-@10) */
  w10  = (w09-w10);
  /* #17: @11 = @6[6] */
  for (rr=(&w11), cs=w06+6; cs!=w06+7; cs+=1) *rr++ = *cs;
  /* #18: @10 = (@10/@11) */
  w10 /= w11;
  /* #19: @12 = sq(@10) */
  w12 = casadi_sq( w10 );
  /* #20: @8 = (@8+@12) */
  w08 += w12;
  /* #21: @12 = @0[2] */
  for (rr=(&w12), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #22: @13 = @4[12] */
  for (rr=(&w13), cs=w04+12; cs!=w04+13; cs+=1) *rr++ = *cs;
  /* #23: @13 = (@12-@13) */
  w13  = (w12-w13);
  /* #24: @14 = @6[12] */
  for (rr=(&w14), cs=w06+12; cs!=w06+13; cs+=1) *rr++ = *cs;
  /* #25: @13 = (@13/@14) */
  w13 /= w14;
  /* #26: @15 = sq(@13) */
  w15 = casadi_sq( w13 );
  /* #27: @8 = (@8+@15) */
  w08 += w15;
  /* #28: output[0][0] = @8 */
  if (res[0]) res[0][0] = w08;
  /* #29: @8 = @4[1] */
  for (rr=(&w08), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #30: @8 = (@1-@8) */
  w08  = (w01-w08);
  /* #31: @15 = @6[1] */
  for (rr=(&w15), cs=w06+1; cs!=w06+2; cs+=1) *rr++ = *cs;
  /* #32: @8 = (@8/@15) */
  w08 /= w15;
  /* #33: @16 = sq(@8) */
  w16 = casadi_sq( w08 );
  /* #34: @17 = @4[7] */
  for (rr=(&w17), cs=w04+7; cs!=w04+8; cs+=1) *rr++ = *cs;
  /* #35: @17 = (@9-@17) */
  w17  = (w09-w17);
  /* #36: @18 = @6[7] */
  for (rr=(&w18), cs=w06+7; cs!=w06+8; cs+=1) *rr++ = *cs;
  /* #37: @17 = (@17/@18) */
  w17 /= w18;
  /* #38: @19 = sq(@17) */
  w19 = casadi_sq( w17 );
  /* #39: @16 = (@16+@19) */
  w16 += w19;
  /* #40: @19 = @4[13] */
  for (rr=(&w19), cs=w04+13; cs!=w04+14; cs+=1) *rr++ = *cs;
  /* #41: @19 = (@12-@19) */
  w19  = (w12-w19);
  /* #42: @20 = @6[13] */
  for (rr=(&w20), cs=w06+13; cs!=w06+14; cs+=1) *rr++ = *cs;
  /* #43: @19 = (@19/@20) */
  w19 /= w20;
  /* #44: @21 = sq(@19) */
  w21 = casadi_sq( w19 );
  /* #45: @16 = (@16+@21) */
  w16 += w21;
  /* #46: output[0][1] = @16 */
  if (res[0]) res[0][1] = w16;
  /* #47: @16 = @4[2] */
  for (rr=(&w16), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #48: @16 = (@1-@16) */
  w16  = (w01-w16);
  /* #49: @21 = @6[2] */
  for (rr=(&w21), cs=w06+2; cs!=w06+3; cs+=1) *rr++ = *cs;
  /* #50: @16 = (@16/@21) */
  w16 /= w21;
  /* #51: @22 = sq(@16) */
  w22 = casadi_sq( w16 );
  /* #52: @23 = @4[8] */
  for (rr=(&w23), cs=w04+8; cs!=w04+9; cs+=1) *rr++ = *cs;
  /* #53: @23 = (@9-@23) */
  w23  = (w09-w23);
  /* #54: @24 = @6[8] */
  for (rr=(&w24), cs=w06+8; cs!=w06+9; cs+=1) *rr++ = *cs;
  /* #55: @23 = (@23/@24) */
  w23 /= w24;
  /* #56: @25 = sq(@23) */
  w25 = casadi_sq( w23 );
  /* #57: @22 = (@22+@25) */
  w22 += w25;
  /* #58: @25 = @4[14] */
  for (rr=(&w25), cs=w04+14; cs!=w04+15; cs+=1) *rr++ = *cs;
  /* #59: @25 = (@12-@25) */
  w25  = (w12-w25);
  /* #60: @26 = @6[14] */
  for (rr=(&w26), cs=w06+14; cs!=w06+15; cs+=1) *rr++ = *cs;
  /* #61: @25 = (@25/@26) */
  w25 /= w26;
  /* #62: @27 = sq(@25) */
  w27 = casadi_sq( w25 );
  /* #63: @22 = (@22+@27) */
  w22 += w27;
  /* #64: output[0][2] = @22 */
  if (res[0]) res[0][2] = w22;
  /* #65: @22 = @4[3] */
  for (rr=(&w22), cs=w04+3; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #66: @22 = (@1-@22) */
  w22  = (w01-w22);
  /* #67: @27 = @6[3] */
  for (rr=(&w27), cs=w06+3; cs!=w06+4; cs+=1) *rr++ = *cs;
  /* #68: @22 = (@22/@27) */
  w22 /= w27;
  /* #69: @28 = sq(@22) */
  w28 = casadi_sq( w22 );
  /* #70: @29 = @4[9] */
  for (rr=(&w29), cs=w04+9; cs!=w04+10; cs+=1) *rr++ = *cs;
  /* #71: @29 = (@9-@29) */
  w29  = (w09-w29);
  /* #72: @30 = @6[9] */
  for (rr=(&w30), cs=w06+9; cs!=w06+10; cs+=1) *rr++ = *cs;
  /* #73: @29 = (@29/@30) */
  w29 /= w30;
  /* #74: @31 = sq(@29) */
  w31 = casadi_sq( w29 );
  /* #75: @28 = (@28+@31) */
  w28 += w31;
  /* #76: @31 = @4[15] */
  for (rr=(&w31), cs=w04+15; cs!=w04+16; cs+=1) *rr++ = *cs;
  /* #77: @31 = (@12-@31) */
  w31  = (w12-w31);
  /* #78: @32 = @6[15] */
  for (rr=(&w32), cs=w06+15; cs!=w06+16; cs+=1) *rr++ = *cs;
  /* #79: @31 = (@31/@32) */
  w31 /= w32;
  /* #80: @33 = sq(@31) */
  w33 = casadi_sq( w31 );
  /* #81: @28 = (@28+@33) */
  w28 += w33;
  /* #82: output[0][3] = @28 */
  if (res[0]) res[0][3] = w28;
  /* #83: @28 = @4[4] */
  for (rr=(&w28), cs=w04+4; cs!=w04+5; cs+=1) *rr++ = *cs;
  /* #84: @28 = (@1-@28) */
  w28  = (w01-w28);
  /* #85: @33 = @6[4] */
  for (rr=(&w33), cs=w06+4; cs!=w06+5; cs+=1) *rr++ = *cs;
  /* #86: @28 = (@28/@33) */
  w28 /= w33;
  /* #87: @34 = sq(@28) */
  w34 = casadi_sq( w28 );
  /* #88: @35 = @4[10] */
  for (rr=(&w35), cs=w04+10; cs!=w04+11; cs+=1) *rr++ = *cs;
  /* #89: @35 = (@9-@35) */
  w35  = (w09-w35);
  /* #90: @36 = @6[10] */
  for (rr=(&w36), cs=w06+10; cs!=w06+11; cs+=1) *rr++ = *cs;
  /* #91: @35 = (@35/@36) */
  w35 /= w36;
  /* #92: @37 = sq(@35) */
  w37 = casadi_sq( w35 );
  /* #93: @34 = (@34+@37) */
  w34 += w37;
  /* #94: @37 = @4[16] */
  for (rr=(&w37), cs=w04+16; cs!=w04+17; cs+=1) *rr++ = *cs;
  /* #95: @37 = (@12-@37) */
  w37  = (w12-w37);
  /* #96: @38 = @6[16] */
  for (rr=(&w38), cs=w06+16; cs!=w06+17; cs+=1) *rr++ = *cs;
  /* #97: @37 = (@37/@38) */
  w37 /= w38;
  /* #98: @39 = sq(@37) */
  w39 = casadi_sq( w37 );
  /* #99: @34 = (@34+@39) */
  w34 += w39;
  /* #100: output[0][4] = @34 */
  if (res[0]) res[0][4] = w34;
  /* #101: @34 = @4[5] */
  for (rr=(&w34), cs=w04+5; cs!=w04+6; cs+=1) *rr++ = *cs;
  /* #102: @1 = (@1-@34) */
  w01 -= w34;
  /* #103: @34 = @6[5] */
  for (rr=(&w34), cs=w06+5; cs!=w06+6; cs+=1) *rr++ = *cs;
  /* #104: @1 = (@1/@34) */
  w01 /= w34;
  /* #105: @39 = sq(@1) */
  w39 = casadi_sq( w01 );
  /* #106: @40 = @4[11] */
  for (rr=(&w40), cs=w04+11; cs!=w04+12; cs+=1) *rr++ = *cs;
  /* #107: @9 = (@9-@40) */
  w09 -= w40;
  /* #108: @40 = @6[11] */
  for (rr=(&w40), cs=w06+11; cs!=w06+12; cs+=1) *rr++ = *cs;
  /* #109: @9 = (@9/@40) */
  w09 /= w40;
  /* #110: @41 = sq(@9) */
  w41 = casadi_sq( w09 );
  /* #111: @39 = (@39+@41) */
  w39 += w41;
  /* #112: @41 = @4[17] */
  for (rr=(&w41), cs=w04+17; cs!=w04+18; cs+=1) *rr++ = *cs;
  /* #113: @12 = (@12-@41) */
  w12 -= w41;
  /* #114: @41 = @6[17] */
  for (rr=(&w41), cs=w06+17; cs!=w06+18; cs+=1) *rr++ = *cs;
  /* #115: @12 = (@12/@41) */
  w12 /= w41;
  /* #116: @42 = sq(@12) */
  w42 = casadi_sq( w12 );
  /* #117: @39 = (@39+@42) */
  w39 += w42;
  /* #118: output[0][5] = @39 */
  if (res[0]) res[0][5] = w39;
  /* #119: @6 = zeros(9x6,18nz) */
  casadi_clear(w06, 18);
  /* #120: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #121: @43 = ones(9x1,7nz) */
  casadi_fill(w43, 7, 1.);
  /* #122: {NULL, @44} = vertsplit(@43) */
  casadi_copy(w43+3, 4, w44);
  /* #123: @39 = @44[0] */
  for (rr=(&w39), cs=w44+0; cs!=w44+1; cs+=1) *rr++ = *cs;
  /* #124: @7 = (@39/@7) */
  w07  = (w39/w07);
  /* #125: @5 = (@5*@7) */
  w05 *= w07;
  /* #126: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #127: @15 = (@39/@15) */
  w15  = (w39/w15);
  /* #128: @8 = (@8*@15) */
  w08 *= w15;
  /* #129: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #130: @21 = (@39/@21) */
  w21  = (w39/w21);
  /* #131: @16 = (@16*@21) */
  w16 *= w21;
  /* #132: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #133: @27 = (@39/@27) */
  w27  = (w39/w27);
  /* #134: @22 = (@22*@27) */
  w22 *= w27;
  /* #135: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #136: @33 = (@39/@33) */
  w33  = (w39/w33);
  /* #137: @28 = (@28*@33) */
  w28 *= w33;
  /* #138: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #139: @39 = (@39/@34) */
  w39 /= w34;
  /* #140: @1 = (@1*@39) */
  w01 *= w39;
  /* #141: @0 = vertcat(@5, @8, @16, @22, @28, @1) */
  rr=w00;
  *rr++ = w05;
  *rr++ = w08;
  *rr++ = w16;
  *rr++ = w22;
  *rr++ = w28;
  *rr++ = w01;
  /* #142: (@6[:18:3] = @0) */
  for (rr=w06+0, cs=w00; rr!=w06+18; rr+=3) *rr = *cs++;
  /* #143: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #144: @5 = ones(9x1,1nz) */
  w05 = 1.;
  /* #145: {NULL, @8} = vertsplit(@5) */
  w08 = w05;
  /* #146: @5 = @8[0] */
  for (rr=(&w05), cs=(&w08)+0; cs!=(&w08)+1; cs+=1) *rr++ = *cs;
  /* #147: @11 = (@5/@11) */
  w11  = (w05/w11);
  /* #148: @10 = (@10*@11) */
  w10 *= w11;
  /* #149: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #150: @18 = (@5/@18) */
  w18  = (w05/w18);
  /* #151: @17 = (@17*@18) */
  w17 *= w18;
  /* #152: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #153: @24 = (@5/@24) */
  w24  = (w05/w24);
  /* #154: @23 = (@23*@24) */
  w23 *= w24;
  /* #155: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #156: @30 = (@5/@30) */
  w30  = (w05/w30);
  /* #157: @29 = (@29*@30) */
  w29 *= w30;
  /* #158: @35 = (2.*@35) */
  w35 = (2.* w35 );
  /* #159: @36 = (@5/@36) */
  w36  = (w05/w36);
  /* #160: @35 = (@35*@36) */
  w35 *= w36;
  /* #161: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #162: @5 = (@5/@40) */
  w05 /= w40;
  /* #163: @9 = (@9*@5) */
  w09 *= w05;
  /* #164: @0 = vertcat(@10, @17, @23, @29, @35, @9) */
  rr=w00;
  *rr++ = w10;
  *rr++ = w17;
  *rr++ = w23;
  *rr++ = w29;
  *rr++ = w35;
  *rr++ = w09;
  /* #165: (@6[1:19:3] = @0) */
  for (rr=w06+1, cs=w00; rr!=w06+19; rr+=3) *rr = *cs++;
  /* #166: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #167: @10 = ones(9x1,1nz) */
  w10 = 1.;
  /* #168: {NULL, @17} = vertsplit(@10) */
  w17 = w10;
  /* #169: @10 = @17[0] */
  for (rr=(&w10), cs=(&w17)+0; cs!=(&w17)+1; cs+=1) *rr++ = *cs;
  /* #170: @14 = (@10/@14) */
  w14  = (w10/w14);
  /* #171: @13 = (@13*@14) */
  w13 *= w14;
  /* #172: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #173: @20 = (@10/@20) */
  w20  = (w10/w20);
  /* #174: @19 = (@19*@20) */
  w19 *= w20;
  /* #175: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #176: @26 = (@10/@26) */
  w26  = (w10/w26);
  /* #177: @25 = (@25*@26) */
  w25 *= w26;
  /* #178: @31 = (2.*@31) */
  w31 = (2.* w31 );
  /* #179: @32 = (@10/@32) */
  w32  = (w10/w32);
  /* #180: @31 = (@31*@32) */
  w31 *= w32;
  /* #181: @37 = (2.*@37) */
  w37 = (2.* w37 );
  /* #182: @38 = (@10/@38) */
  w38  = (w10/w38);
  /* #183: @37 = (@37*@38) */
  w37 *= w38;
  /* #184: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #185: @10 = (@10/@41) */
  w10 /= w41;
  /* #186: @12 = (@12*@10) */
  w12 *= w10;
  /* #187: @0 = vertcat(@13, @19, @25, @31, @37, @12) */
  rr=w00;
  *rr++ = w13;
  *rr++ = w19;
  *rr++ = w25;
  *rr++ = w31;
  *rr++ = w37;
  *rr++ = w12;
  /* #188: (@6[2:20:3] = @0) */
  for (rr=w06+2, cs=w00; rr!=w06+20; rr+=3) *rr = *cs++;
  /* #189: output[1][0] = @6 */
  casadi_copy(w06, 18, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int landing2_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int landing2_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int landing2_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void landing2_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int landing2_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void landing2_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void landing2_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void landing2_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int landing2_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int landing2_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real landing2_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* landing2_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* landing2_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* landing2_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* landing2_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int landing2_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 145;
  return 0;
}

CASADI_SYMBOL_EXPORT int landing2_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 145*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
