/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) landing2_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {36, 1, 1};

static const casadi_real casadi_zeros[36] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* landing2_constr_h_fun:(i0[6],i1[3],i2[0],i3[36])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *w00=w+0, w01, *w04=w+61, w05, *w06=w+80, w07, w08, w09, w10;
  const casadi_real *cs, *wr02, *wr03;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 6, w00);
  /* #1: @1 = @0[0] */
  for (rr=(&w01), cs=w00+0; cs!=w00+1; cs+=1) *rr++ = *cs;
  /* #2: @2 = input[3][0] */
  wr02 = arg[3] ? arg[3] : casadi_zeros;
  /* #3: @3 = @2[:18] */
  wr03 = wr02+0;
  /* #4: @3 = reshape(@3) */
  /* #5: @4 = @3' */
  for (i=0, rr=w04, cs=wr03; i<6; ++i) for (j=0; j<3; ++j) rr[i+j*6] = *cs++;
  /* #6: @5 = @4[0] */
  for (rr=(&w05), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #7: @5 = (@1-@5) */
  w05  = (w01-w05);
  /* #8: @3 = @2[18:36] */
  wr03 = wr02+18;
  /* #9: @3 = reshape(@3) */
  /* #10: @6 = @3' */
  for (i=0, rr=w06, cs=wr03; i<6; ++i) for (j=0; j<3; ++j) rr[i+j*6] = *cs++;
  /* #11: @7 = @6[0] */
  for (rr=(&w07), cs=w06+0; cs!=w06+1; cs+=1) *rr++ = *cs;
  /* #12: @5 = (@5/@7) */
  w05 /= w07;
  /* #13: @5 = sq(@5) */
  w05 = casadi_sq( w05 );
  /* #14: @7 = @0[1] */
  for (rr=(&w07), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #15: @8 = @4[6] */
  for (rr=(&w08), cs=w04+6; cs!=w04+7; cs+=1) *rr++ = *cs;
  /* #16: @8 = (@7-@8) */
  w08  = (w07-w08);
  /* #17: @9 = @6[6] */
  for (rr=(&w09), cs=w06+6; cs!=w06+7; cs+=1) *rr++ = *cs;
  /* #18: @8 = (@8/@9) */
  w08 /= w09;
  /* #19: @8 = sq(@8) */
  w08 = casadi_sq( w08 );
  /* #20: @5 = (@5+@8) */
  w05 += w08;
  /* #21: @8 = @0[2] */
  for (rr=(&w08), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #22: @9 = @4[12] */
  for (rr=(&w09), cs=w04+12; cs!=w04+13; cs+=1) *rr++ = *cs;
  /* #23: @9 = (@8-@9) */
  w09  = (w08-w09);
  /* #24: @10 = @6[12] */
  for (rr=(&w10), cs=w06+12; cs!=w06+13; cs+=1) *rr++ = *cs;
  /* #25: @9 = (@9/@10) */
  w09 /= w10;
  /* #26: @9 = sq(@9) */
  w09 = casadi_sq( w09 );
  /* #27: @5 = (@5+@9) */
  w05 += w09;
  /* #28: output[0][0] = @5 */
  if (res[0]) res[0][0] = w05;
  /* #29: @5 = @4[1] */
  for (rr=(&w05), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #30: @5 = (@1-@5) */
  w05  = (w01-w05);
  /* #31: @9 = @6[1] */
  for (rr=(&w09), cs=w06+1; cs!=w06+2; cs+=1) *rr++ = *cs;
  /* #32: @5 = (@5/@9) */
  w05 /= w09;
  /* #33: @5 = sq(@5) */
  w05 = casadi_sq( w05 );
  /* #34: @9 = @4[7] */
  for (rr=(&w09), cs=w04+7; cs!=w04+8; cs+=1) *rr++ = *cs;
  /* #35: @9 = (@7-@9) */
  w09  = (w07-w09);
  /* #36: @10 = @6[7] */
  for (rr=(&w10), cs=w06+7; cs!=w06+8; cs+=1) *rr++ = *cs;
  /* #37: @9 = (@9/@10) */
  w09 /= w10;
  /* #38: @9 = sq(@9) */
  w09 = casadi_sq( w09 );
  /* #39: @5 = (@5+@9) */
  w05 += w09;
  /* #40: @9 = @4[13] */
  for (rr=(&w09), cs=w04+13; cs!=w04+14; cs+=1) *rr++ = *cs;
  /* #41: @9 = (@8-@9) */
  w09  = (w08-w09);
  /* #42: @10 = @6[13] */
  for (rr=(&w10), cs=w06+13; cs!=w06+14; cs+=1) *rr++ = *cs;
  /* #43: @9 = (@9/@10) */
  w09 /= w10;
  /* #44: @9 = sq(@9) */
  w09 = casadi_sq( w09 );
  /* #45: @5 = (@5+@9) */
  w05 += w09;
  /* #46: output[0][1] = @5 */
  if (res[0]) res[0][1] = w05;
  /* #47: @5 = @4[2] */
  for (rr=(&w05), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #48: @5 = (@1-@5) */
  w05  = (w01-w05);
  /* #49: @9 = @6[2] */
  for (rr=(&w09), cs=w06+2; cs!=w06+3; cs+=1) *rr++ = *cs;
  /* #50: @5 = (@5/@9) */
  w05 /= w09;
  /* #51: @5 = sq(@5) */
  w05 = casadi_sq( w05 );
  /* #52: @9 = @4[8] */
  for (rr=(&w09), cs=w04+8; cs!=w04+9; cs+=1) *rr++ = *cs;
  /* #53: @9 = (@7-@9) */
  w09  = (w07-w09);
  /* #54: @10 = @6[8] */
  for (rr=(&w10), cs=w06+8; cs!=w06+9; cs+=1) *rr++ = *cs;
  /* #55: @9 = (@9/@10) */
  w09 /= w10;
  /* #56: @9 = sq(@9) */
  w09 = casadi_sq( w09 );
  /* #57: @5 = (@5+@9) */
  w05 += w09;
  /* #58: @9 = @4[14] */
  for (rr=(&w09), cs=w04+14; cs!=w04+15; cs+=1) *rr++ = *cs;
  /* #59: @9 = (@8-@9) */
  w09  = (w08-w09);
  /* #60: @10 = @6[14] */
  for (rr=(&w10), cs=w06+14; cs!=w06+15; cs+=1) *rr++ = *cs;
  /* #61: @9 = (@9/@10) */
  w09 /= w10;
  /* #62: @9 = sq(@9) */
  w09 = casadi_sq( w09 );
  /* #63: @5 = (@5+@9) */
  w05 += w09;
  /* #64: output[0][2] = @5 */
  if (res[0]) res[0][2] = w05;
  /* #65: @5 = @4[3] */
  for (rr=(&w05), cs=w04+3; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #66: @5 = (@1-@5) */
  w05  = (w01-w05);
  /* #67: @9 = @6[3] */
  for (rr=(&w09), cs=w06+3; cs!=w06+4; cs+=1) *rr++ = *cs;
  /* #68: @5 = (@5/@9) */
  w05 /= w09;
  /* #69: @5 = sq(@5) */
  w05 = casadi_sq( w05 );
  /* #70: @9 = @4[9] */
  for (rr=(&w09), cs=w04+9; cs!=w04+10; cs+=1) *rr++ = *cs;
  /* #71: @9 = (@7-@9) */
  w09  = (w07-w09);
  /* #72: @10 = @6[9] */
  for (rr=(&w10), cs=w06+9; cs!=w06+10; cs+=1) *rr++ = *cs;
  /* #73: @9 = (@9/@10) */
  w09 /= w10;
  /* #74: @9 = sq(@9) */
  w09 = casadi_sq( w09 );
  /* #75: @5 = (@5+@9) */
  w05 += w09;
  /* #76: @9 = @4[15] */
  for (rr=(&w09), cs=w04+15; cs!=w04+16; cs+=1) *rr++ = *cs;
  /* #77: @9 = (@8-@9) */
  w09  = (w08-w09);
  /* #78: @10 = @6[15] */
  for (rr=(&w10), cs=w06+15; cs!=w06+16; cs+=1) *rr++ = *cs;
  /* #79: @9 = (@9/@10) */
  w09 /= w10;
  /* #80: @9 = sq(@9) */
  w09 = casadi_sq( w09 );
  /* #81: @5 = (@5+@9) */
  w05 += w09;
  /* #82: output[0][3] = @5 */
  if (res[0]) res[0][3] = w05;
  /* #83: @5 = @4[4] */
  for (rr=(&w05), cs=w04+4; cs!=w04+5; cs+=1) *rr++ = *cs;
  /* #84: @5 = (@1-@5) */
  w05  = (w01-w05);
  /* #85: @9 = @6[4] */
  for (rr=(&w09), cs=w06+4; cs!=w06+5; cs+=1) *rr++ = *cs;
  /* #86: @5 = (@5/@9) */
  w05 /= w09;
  /* #87: @5 = sq(@5) */
  w05 = casadi_sq( w05 );
  /* #88: @9 = @4[10] */
  for (rr=(&w09), cs=w04+10; cs!=w04+11; cs+=1) *rr++ = *cs;
  /* #89: @9 = (@7-@9) */
  w09  = (w07-w09);
  /* #90: @10 = @6[10] */
  for (rr=(&w10), cs=w06+10; cs!=w06+11; cs+=1) *rr++ = *cs;
  /* #91: @9 = (@9/@10) */
  w09 /= w10;
  /* #92: @9 = sq(@9) */
  w09 = casadi_sq( w09 );
  /* #93: @5 = (@5+@9) */
  w05 += w09;
  /* #94: @9 = @4[16] */
  for (rr=(&w09), cs=w04+16; cs!=w04+17; cs+=1) *rr++ = *cs;
  /* #95: @9 = (@8-@9) */
  w09  = (w08-w09);
  /* #96: @10 = @6[16] */
  for (rr=(&w10), cs=w06+16; cs!=w06+17; cs+=1) *rr++ = *cs;
  /* #97: @9 = (@9/@10) */
  w09 /= w10;
  /* #98: @9 = sq(@9) */
  w09 = casadi_sq( w09 );
  /* #99: @5 = (@5+@9) */
  w05 += w09;
  /* #100: output[0][4] = @5 */
  if (res[0]) res[0][4] = w05;
  /* #101: @5 = @4[5] */
  for (rr=(&w05), cs=w04+5; cs!=w04+6; cs+=1) *rr++ = *cs;
  /* #102: @1 = (@1-@5) */
  w01 -= w05;
  /* #103: @5 = @6[5] */
  for (rr=(&w05), cs=w06+5; cs!=w06+6; cs+=1) *rr++ = *cs;
  /* #104: @1 = (@1/@5) */
  w01 /= w05;
  /* #105: @1 = sq(@1) */
  w01 = casadi_sq( w01 );
  /* #106: @5 = @4[11] */
  for (rr=(&w05), cs=w04+11; cs!=w04+12; cs+=1) *rr++ = *cs;
  /* #107: @7 = (@7-@5) */
  w07 -= w05;
  /* #108: @5 = @6[11] */
  for (rr=(&w05), cs=w06+11; cs!=w06+12; cs+=1) *rr++ = *cs;
  /* #109: @7 = (@7/@5) */
  w07 /= w05;
  /* #110: @7 = sq(@7) */
  w07 = casadi_sq( w07 );
  /* #111: @1 = (@1+@7) */
  w01 += w07;
  /* #112: @7 = @4[17] */
  for (rr=(&w07), cs=w04+17; cs!=w04+18; cs+=1) *rr++ = *cs;
  /* #113: @8 = (@8-@7) */
  w08 -= w07;
  /* #114: @7 = @6[17] */
  for (rr=(&w07), cs=w06+17; cs!=w06+18; cs+=1) *rr++ = *cs;
  /* #115: @8 = (@8/@7) */
  w08 /= w07;
  /* #116: @8 = sq(@8) */
  w08 = casadi_sq( w08 );
  /* #117: @1 = (@1+@8) */
  w01 += w08;
  /* #118: output[0][5] = @1 */
  if (res[0]) res[0][5] = w01;
  return 0;
}

CASADI_SYMBOL_EXPORT int landing2_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int landing2_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int landing2_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void landing2_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int landing2_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void landing2_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void landing2_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void landing2_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int landing2_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int landing2_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real landing2_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* landing2_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* landing2_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* landing2_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* landing2_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int landing2_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 102;
  return 0;
}

CASADI_SYMBOL_EXPORT int landing2_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 102*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
